"""Add enterprise models

Revision ID: ef7f5d864c73
Revises: 1b50d484a996
Create Date: 2026-07-19 20:45:32.164243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7f5d864c73'
down_revision: Union[str, None] = '1b50d484a996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('communication_score', sa.Float(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_title', sa.String(length=255), nullable=False),
    sa.Column('item_link', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('weekly_goal', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('evaluation_feedback', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('analysis_results', sa.Column('ats_keyword_suggestions', sa.JSON(), nullable=True))
    op.add_column('assessments', sa.Column('difficulty', sa.String(length=50), nullable=False, server_default='Medium'))
    op.add_column('assessments', sa.Column('time_limit', sa.Integer(), nullable=False, server_default='600'))
    op.add_column('job_descriptions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('job_descriptions', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('salary_estimate', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('missing_experience_analysis', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'job_descriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('resumes', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('resumes', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('resumes', sa.Column('optimization_suggestions', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('ats_keyword_suggestions', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('career_goals', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_roles', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferred_locations', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('achievements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'achievements')
    op.drop_column('users', 'education')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'preferred_locations')
    op.drop_column('users', 'preferred_roles')
    op.drop_column('users', 'career_goals')
    op.drop_column('users', 'is_admin')
    op.drop_column('resumes', 'ats_keyword_suggestions')
    op.drop_column('resumes', 'optimization_suggestions')
    op.drop_column('resumes', 'is_active')
    op.drop_column('resumes', 'version')
    op.drop_constraint(None, 'job_descriptions', type_='foreignkey')
    op.drop_column('job_descriptions', 'missing_experience_analysis')
    op.drop_column('job_descriptions', 'salary_estimate')
    op.drop_column('job_descriptions', 'company')
    op.drop_column('job_descriptions', 'user_id')
    op.drop_column('assessments', 'time_limit')
    op.drop_column('assessments', 'difficulty')
    op.drop_column('analysis_results', 'ats_keyword_suggestions')
    op.drop_table('interview_questions')
    op.drop_table('notifications')
    op.drop_table('learning_progress')
    op.drop_table('interview_attempts')
    # ### end Alembic commands ###
